% Authored Prolog source for node n1 ("Clara") in the typed-edges live E2E.
% This is the exact source that ran in the verified 2026-07-05 E2E described
% in docs/ritual_typed_edges.md ("Verification / Live E2E").
%
% consult_clara_groq/2 is NOT authored here — it is generated by edge
% transduction from the `offering` edge n1 -> n2 in graph_layout.json and
% merged with this source at activation:
%
%   consult_clara_groq(Payload, Result) :-
%       caws_consult('n2', 'consults/e1', Payload, Result).
%
% The reply surfaces as a dict; on Tabu or patience timeout the consult
% FAILS (timeout-to-false), so reasoned_response/3 fails cleanly rather
% than blocking convergence.

reasoned_response(Query, Context, Response) :-
    ponder_text_with_context(Query, Context, ClaraAnswer),
    consult_clara_groq(_{prompt: Query}, GroqReply),
    (   catch((get_dict(response, GroqReply, R1), get_dict(content, R1, GroqAnswer)), _, fail)
    ->  true
    ;   term_to_atom(GroqReply, GroqAnswer)
    ),
    format(atom(Synth), "Two answers to the question '~w' follow. Reconcile them into one short, best answer.~nAnswer A: ~w~nAnswer B: ~w", [Query, ClaraAnswer, GroqAnswer]),
    ponder_text_with_context(Synth, Context, Response).
